### ISSUE TITLE
[New Listing] Description field can expand out of bounds + font

### ISSUE THREAD

**Issue by thebeyondr** [trustlist/trustlist#38]
> desc-box-doesnt-care-about-rules.jpg
![image](https://github.com/trustlist/trustlist/assets/19380973/1735fc22-fe11-468b-9d53-7689f88c0fbf)

Proposal:
- [ ] Limit desc box to modal bounds
- [ ] Update font to be consistent with the rest of the site, its monospace at time of writing:
![image](https://github.com/trustlist/trustlist/assets/19380973/0e87043a-d1bd-4210-9738-c3f7f905e1fd)

**Comment by ChialiT** [comment]
What about the lemonade stand~~ XD @thebeyondr
