### ISSUE TITLE
[Epoch] User isn't prompted to transition before making a listing

### ISSUE THREAD

**Issue by thebeyondr** [trustlist/trustlist#43]
Users are not alerted when new identities are available (epoch transition) and so can end up trying to make a listing, getting an error, and having to start over. they are also not directed to where they should do this transition or why its necessary.

![image](https://github.com/trustlist/trustlist/assets/19380973/9a63b08d-ee05-4059-98c8-c86d8cae234f)

Proposal:

- [ ] Alert users on epoch transition
- [ ] Place transition button closer to the the epoch timing context. (will be changed when #36 is addressed)
![image](https://github.com/trustlist/trustlist/assets/19380973/4edac5c2-de66-498e-9870-7fb1a73d535e)

**Comment by CJ-Rose** [comment]
i think the smoothest way to handle this will be to include an alert to the user when they open modals to post or make an offer, and include an additional transition button there.
